import { Category, Ticket, KnowledgeArticle, ServiceStatus, User, SecurityLog } from './types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-btik-001',
    name: 'Ir. Haryanto, M.T.',
    email: 'haryanto@upitra.ac.id',
    password: 'upitra123',
    role: 'ADMIN',
    identifier: 'BTIK-001',
    department: 'Kepala Biro TIK',
    phone: '081234567890',
    isActive: true,
    lastLoginAt: new Date().toISOString(),
    createdAt: '2026-01-10T08:00:00.000Z',
  },
  {
    id: 'usr-btik-002',
    name: 'Robertus Wijaya, S.Kom.',
    email: 'robertus.w@upitra.ac.id',
    password: 'upitra123',
    role: 'TECHNICIAN',
    identifier: 'BTIK-004',
    department: 'Infrastruktur & Jaringan',
    phone: '081234567891',
    isActive: true,
    lastLoginAt: new Date(Date.now() - 3600 * 1000).toISOString(),
    createdAt: '2026-01-15T08:00:00.000Z',
  },
  {
    id: 'usr-btik-003',
    name: 'Kevin Triputra, S.Inf.',
    email: 'kevin.t@upitra.ac.id',
    password: 'upitra123',
    role: 'TECHNICIAN',
    identifier: 'BTIK-007',
    department: 'Sistem Informasi & Aplikasi',
    phone: '081234567892',
    isActive: true,
    lastLoginAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    createdAt: '2026-02-01T08:00:00.000Z',
  },
  {
    id: 'usr-dsn-001',
    name: 'Dr. Maria Yosephine, M.Kom.',
    email: 'maria.yosephine@upitra.ac.id',
    password: 'upitra123',
    role: 'LECTURER',
    identifier: '0612088501',
    department: 'S1 Sistem Informasi',
    phone: '081398765432',
    isActive: true,
    lastLoginAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    createdAt: '2026-02-10T08:00:00.000Z',
  },
  {
    id: 'usr-mhs-001',
    name: 'Budi Santoso',
    email: 'budi.santoso@student.upitra.ac.id',
    password: 'upitra123',
    role: 'STUDENT',
    identifier: '2023010045',
    department: 'S1 Informatika',
    phone: '081512345678',
    isActive: true,
    lastLoginAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    createdAt: '2026-03-01T08:00:00.000Z',
  },
  {
    id: 'usr-mhs-002',
    name: 'Anastasia Putri',
    email: 'anastasia.p@student.upitra.ac.id',
    password: 'upitra123',
    role: 'STUDENT',
    identifier: '2024010112',
    department: 'S1 Manajemen Bisnis',
    phone: '08177889900',
    isActive: true,
    lastLoginAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    createdAt: '2026-03-05T08:00:00.000Z',
  },
  {
    id: 'usr-spm-001',
    name: 'Akun Usil Terblokir',
    email: 'iseng@student.upitra.ac.id',
    password: 'upitra123',
    role: 'STUDENT',
    identifier: '2023019999',
    department: 'S1 Informatika',
    phone: '08999999999',
    isActive: false, // Suspended account due to spam
    lastLoginAt: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
    createdAt: '2026-03-10T08:00:00.000Z',
  },
];

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 1,
    name: 'Jaringan & WiFi Kampus',
    description: 'Kendala koneksi internet, WiFi UPITRA-Hotspot, port LAN, dan akses eduroam',
    icon: 'Wifi',
    slaHours: 4,
    isActive: true,
  },
  {
    id: 2,
    name: 'SIAKAD & Sistem Akademik',
    description: 'Masalah login, KRS error, sync nilai, dan data kemahasiswaan',
    icon: 'GraduationCap',
    slaHours: 6,
    isActive: true,
  },
  {
    id: 3,
    name: 'LMS & Kuliah Online',
    description: 'Akses e-learning Moodle, sinkronisasi mata kuliah, dan submission tugas',
    icon: 'BookOpen',
    slaHours: 6,
    isActive: true,
  },
  {
    id: 4,
    name: 'Akun & Email Institusi',
    description: 'Aktivasi @student.upitra.ac.id, lisensi Microsoft 365, reset password SSO',
    icon: 'Mail',
    slaHours: 8,
    isActive: true,
  },
  {
    id: 5,
    name: 'Hardware & Fasilitas Lab',
    description: 'Kerusakan PC Lab, instalasi software praktikum (SPSS, MATLAB), printer dosen',
    icon: 'Monitor',
    slaHours: 12,
    isActive: true,
  },
  {
    id: 6,
    name: 'Multimedia Ruang Kuliah',
    description: 'Proyektor kelas, sound system auditorium, perlengkapan kuliah hybrid',
    icon: 'Tv',
    slaHours: 2,
    isActive: true,
  },
];

export const INITIAL_SECURITY_LOGS: SecurityLog[] = [
  {
    id: 1,
    ticketNumber: 'UPITRA-2026-0099',
    reporterEmail: 'iseng@student.upitra.ac.id',
    incidentType: 'SPAM_TICKET',
    reason: 'Pengajuan tiket iseng/prank pesan kopi dengan prioritas darurat di kantin bawah',
    actionTaken: 'Tiket ditolak (REJECTED_SPAM) & akun pengguna dinonaktifkan sementara',
    actorName: 'Ir. Haryanto, M.T. (Admin BTIK)',
    ipAddress: '192.168.10.45',
    createdAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
  },
];

export const INITIAL_TICKETS: Ticket[] = [
  {
    id: 'tkt-001',
    ticketNumber: 'UPITRA-2026-0891',
    title: 'Gagal Login SIAKAD untuk Pengisian KRS Semester Ganjil',
    description: 'Muncul notifikasi "Invalid Credential" padahal password sudah sesuai dengan email kampus. Mohon dibantu reset akses sebelum masa KRS ditutup.',
    categoryId: 2,
    category: INITIAL_CATEGORIES[1],
    priority: 'HIGH',
    status: 'IN_PROGRESS',
    requesterName: 'Budi Santoso',
    requesterEmail: 'budi.santoso@student.upitra.ac.id',
    requesterRole: 'Mahasiswa',
    requesterId: '2023010045',
    requesterPhone: '081512345678',
    locationBuilding: 'Gedung A',
    locationRoom: 'Ruang BEM Lantai 2',
    assignedToId: 'usr-btik-003',
    assignedTo: INITIAL_USERS[2],
    slaDueAt: new Date(Date.now() + 4 * 3600 * 1000).toISOString(),
    resolvedAt: null,
    isSpamFlagged: false,
    spamReason: null,
    createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
    messages: [
      {
        id: 1,
        ticketId: 'tkt-001',
        senderName: 'Budi Santoso',
        senderRole: 'Mahasiswa',
        message: 'Selamat pagi tim BTIK, mohon bantuannya karena batas pengisian KRS berakhir besok sore.',
        isInternal: false,
        createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
      },
      {
        id: 2,
        ticketId: 'tkt-001',
        senderName: 'Kevin Triputra, S.Inf.',
        senderRole: 'Teknisi BTIK',
        message: 'Halo Budi, tiket Anda sedang kami periksa pada basis data akun SSO. Mohon pastikan kembali username menggunakan NIM tanpa spasi.',
        isInternal: false,
        createdAt: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
      },
      {
        id: 3,
        ticketId: 'tkt-001',
        senderName: 'Kevin Triputra, S.Inf.',
        senderRole: 'Teknisi BTIK',
        message: 'Catatan internal: Sinkronisasi LDAP SIAKAD sempat delay pasca maintenance jam 02:00 pagi. Sedang re-sync.',
        isInternal: true,
        createdAt: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
      },
    ],
    timelines: [
      {
        id: 1,
        ticketId: 'tkt-001',
        title: 'Tiket Dibuat',
        description: 'Pelapor mengajukan tiket keluhan akses SIAKAD',
        statusCode: 'OPEN',
        actorName: 'Budi Santoso',
        createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
      },
      {
        id: 2,
        ticketId: 'tkt-001',
        title: 'Ditugaskan ke Teknisi',
        description: 'Tiket didelegasikan kepada Kevin Triputra (Sistem Informasi)',
        statusCode: 'IN_PROGRESS',
        actorName: 'Sistem Helpdesk BTIK',
        createdAt: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
      },
    ],
    feedback: null,
  },
  {
    id: 'tkt-002',
    ticketNumber: 'UPITRA-2026-0892',
    title: 'Proyektor Ruang B.302 Berkedip dan Tidak Muncul Sinyal HDMI',
    description: 'Saat kuliah Perancangan Basis Data, proyektor mati setiap 5 menit dan port HDMI di meja dosen longgar.',
    categoryId: 6,
    category: INITIAL_CATEGORIES[5],
    priority: 'CRITICAL',
    status: 'RESOLVED',
    requesterName: 'Dr. Maria Yosephine, M.Kom.',
    requesterEmail: 'maria.yosephine@upitra.ac.id',
    requesterRole: 'Dosen',
    requesterId: '0612088501',
    requesterPhone: '081398765432',
    locationBuilding: 'Gedung B',
    locationRoom: 'Ruang Kelas B.302',
    assignedToId: 'usr-btik-002',
    assignedTo: INITIAL_USERS[1],
    slaDueAt: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
    resolvedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    isSpamFlagged: false,
    spamReason: null,
    createdAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    messages: [
      {
        id: 4,
        ticketId: 'tkt-002',
        senderName: 'Dr. Maria Yosephine, M.Kom.',
        senderRole: 'Dosen',
        message: 'Kondisi proyektor saat ini tidak bisa digunakan untuk mengajar mahasiswa kelas B.302.',
        isInternal: false,
        createdAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
      },
      {
        id: 5,
        ticketId: 'tkt-002',
        senderName: 'Robertus Wijaya, S.Kom.',
        senderRole: 'Teknisi BTIK',
        message: 'Kabel HDMI telah diganti dengan braided gold-plated baru dan proyektor telah dibersihkan filternya. Sudah berfungsi prima.',
        isInternal: false,
        createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
      },
    ],
    timelines: [
      {
        id: 3,
        ticketId: 'tkt-002',
        title: 'Tiket Dibuat',
        description: 'Pelapor melaporkan proyektor ruang kuliah bermasalah',
        statusCode: 'OPEN',
        actorName: 'Dr. Maria Yosephine, M.Kom.',
        createdAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
      },
      {
        id: 4,
        ticketId: 'tkt-002',
        title: 'Penanganan di Lokasi',
        description: 'Teknisi tiba di Ruang B.302 dan mengganti kabel transmisi display',
        statusCode: 'IN_PROGRESS',
        actorName: 'Robertus Wijaya, S.Kom.',
        createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
      },
      {
        id: 5,
        ticketId: 'tkt-002',
        title: 'Kendala Diselesaikan',
        description: 'Proyektor berhasil menampilkan display laptop dosen secara stabil',
        statusCode: 'RESOLVED',
        actorName: 'Robertus Wijaya, S.Kom.',
        createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
      },
    ],
    feedback: {
      id: 1,
      ticketId: 'tkt-002',
      rating: 5,
      comment: 'Respon teknisi sangat cepat, hanya 10 menit langsung hadir ke kelas sehingga kuliah dapat dilanjutkan. Terima kasih BTIK UPITRA!',
      createdAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    },
  },
  {
    id: 'tkt-003',
    ticketNumber: 'UPITRA-2026-0893',
    title: 'Permohonan Aktivasi Lisensi Microsoft 365 Mahasiswa Baru',
    description: 'Membutuhkan akses Microsoft Word dan Excel untuk pengerjaan tugas proyek akhir. Email kampus sudah aktif namun belum dapat login ke Office 365.',
    categoryId: 4,
    category: INITIAL_CATEGORIES[3],
    priority: 'LOW',
    status: 'OPEN',
    requesterName: 'Anastasia Putri',
    requesterEmail: 'anastasia.p@student.upitra.ac.id',
    requesterRole: 'Mahasiswa',
    requesterId: '2024010112',
    requesterPhone: '08177889900',
    locationBuilding: 'Gedung Perpustakaan',
    locationRoom: 'Lantai 1 - Area Baca',
    assignedToId: null,
    assignedTo: null,
    slaDueAt: new Date(Date.now() + 8 * 3600 * 1000).toISOString(),
    resolvedAt: null,
    isSpamFlagged: false,
    spamReason: null,
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    messages: [],
    timelines: [
      {
        id: 6,
        ticketId: 'tkt-003',
        title: 'Tiket Dibuat',
        description: 'Pengajuan aktivasi akun Microsoft 365 baru diterima',
        statusCode: 'OPEN',
        actorName: 'Anastasia Putri',
        createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
      },
    ],
    feedback: null,
  },
  {
    id: 'tkt-004',
    ticketNumber: 'UPITRA-2026-0894',
    title: 'Koneksi WiFi UPITRA-Hotspot di Lab Komputer 2 Sangat Lambat',
    description: 'Kecepatan unduh hanya 0.5 Mbps saat seluruh mahasiswa praktikum mengakses internet. Sering disconnect saat download dataset riset.',
    categoryId: 1,
    category: INITIAL_CATEGORIES[0],
    priority: 'MEDIUM',
    status: 'IN_PROGRESS',
    requesterName: 'Stefanus Kevin',
    requesterEmail: 'kevin.s@student.upitra.ac.id',
    requesterRole: 'Mahasiswa',
    requesterId: '2022010018',
    requesterPhone: '08192837465',
    locationBuilding: 'Gedung A',
    locationRoom: 'Lab Komputer 2 (Lt 3)',
    assignedToId: 'usr-btik-002',
    assignedTo: INITIAL_USERS[1],
    slaDueAt: new Date(Date.now() + 3 * 3600 * 1000).toISOString(),
    resolvedAt: null,
    isSpamFlagged: false,
    spamReason: null,
    createdAt: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    messages: [],
    timelines: [
      {
        id: 7,
        ticketId: 'tkt-004',
        title: 'Tiket Dibuat',
        description: 'Pelaporan kendala throughput access point Lab 2',
        statusCode: 'OPEN',
        actorName: 'Stefanus Kevin',
        createdAt: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
      },
      {
        id: 8,
        ticketId: 'tkt-004',
        title: 'Pemeriksaan Bandwidth AP',
        description: 'Teknisi melakukan analisis channel interferensi pada AP Gedung A',
        statusCode: 'IN_PROGRESS',
        actorName: 'Robertus Wijaya, S.Kom.',
        createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
      },
    ],
    feedback: null,
  },
  {
    id: 'tkt-099',
    ticketNumber: 'UPITRA-2026-0099',
    title: 'Coba tes iseng doang wkwkwk tolong antar es kopi',
    description: 'Mau coba sistem helpdesk aja apakah adminnya galak atau fast respon wkwk',
    categoryId: 1,
    category: INITIAL_CATEGORIES[0],
    priority: 'CRITICAL',
    status: 'REJECTED_SPAM',
    requesterName: 'Akun Usil Terblokir',
    requesterEmail: 'iseng@student.upitra.ac.id',
    requesterRole: 'Mahasiswa',
    requesterId: '2023019999',
    requesterPhone: '08999999999',
    locationBuilding: 'Gedung A',
    locationRoom: 'Kantin Bawah',
    assignedToId: 'usr-btik-001',
    assignedTo: INITIAL_USERS[0],
    slaDueAt: null,
    resolvedAt: null,
    isSpamFlagged: true,
    spamReason: 'Laporan palsu / prank yang menyalahgunakan prioritas darurat',
    createdAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    messages: [
      {
        id: 99,
        ticketId: 'tkt-099',
        senderName: 'Ir. Haryanto, M.T.',
        senderRole: 'Admin BTIK',
        message: 'Tiket ini teridentifikasi sebagai laporan palsu/usil. Tiket ditolak dan akun pelapor dinonaktifkan sementara sesuai SOP BTIK UPITRA.',
        isInternal: true,
        createdAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
      },
    ],
    timelines: [
      {
        id: 99,
        ticketId: 'tkt-099',
        title: 'Tiket Ditolak (Spam/Usil)',
        description: 'Laporan palsu/usil terdeteksi oleh sistem BTIK dan dikeluarkan dari metrik SLA',
        statusCode: 'REJECTED_SPAM',
        actorName: 'Ir. Haryanto, M.T.',
        createdAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
      },
    ],
    feedback: null,
  },
];

export const INITIAL_KB_ARTICLES: KnowledgeArticle[] = [
  {
    id: 1,
    title: 'Cara Menghubungkan Laptop & HP ke WiFi UPITRA-Hotspot',
    category: 'Jaringan & WiFi',
    excerpt: 'Panduan login WiFi kampus dengan akun SSO sivitas akademika Universitas Pignatelli Triputra.',
    content: `### Langkah Koneksi ke WiFi UPITRA-Hotspot:
1. Buka pengaturan WiFi pada perangkat laptop atau ponsel Anda.
2. Pilih SSID: **UPITRA-Hotspot** atau **eduroam** jika memiliki akun roaming antar universitas.
3. Masukkan identitas akun SSO Anda:
   - **Mahasiswa**: Username menggunakan NIM (contoh: 2023010045) dan kata sandi email institusi.
   - **Dosen & Tendik**: Username menggunakan NIP/NIDN.
4. Apabila halaman captive portal tidak muncul otomatis, buka peramban dan kunjungi: \`http://wifi.upitra.ac.id\`.
5. Klik **Masuk** dan nikmati akses internet kampus dengan kuota tak terbatas.`,
    tags: 'wifi, internet, eduroam, login',
    views: 342,
    helpfulCount: 89,
    createdAt: '2026-08-01T08:00:00.000Z',
  },
  {
    id: 2,
    title: 'Panduan Reset Mandiri Password SIAKAD 2.0',
    category: 'Sistem Akademik',
    excerpt: 'Langkah pemulihan kata sandi portal akademik tanpa harus datang langsung ke kantor BTIK.',
    content: `### Cara Reset Password SIAKAD:
1. Akses halaman resmi SIAKAD di \`https://siakad.upitra.ac.id\`.
2. Klik tautan **Lupa Password?** di bawah tombol login.
3. Masukkan alamat email institusi Anda (\`@student.upitra.ac.id\` atau \`@upitra.ac.id\`).
4. Buka inbox email Anda dan temukan surat konfirmasi dari **Biro TIK UPITRA**.
5. Klik tombol verifikasi dan buat kata sandi baru minimal 8 karakter.
6. Coba login kembali ke SIAKAD.`,
    tags: 'siakad, password, reset, login',
    views: 520,
    helpfulCount: 142,
    createdAt: '2026-08-05T09:30:00.000Z',
  },
  {
    id: 3,
    title: 'Aktivasi Lisensi Microsoft 365 Edukasi Gratis',
    category: 'Akun & Software',
    excerpt: 'Petunjuk download dan aktivasi lisensi Office 365 resmi untuk mahasiswa dan dosen UPITRA.',
    content: `### Hak Akses Microsoft 365 UPITRA:
Seluruh sivitas akademika berhak mendapatkan lisensi resmi Office 365 (Word, Excel, PowerPoint, Teams, OneDrive 1TB).

1. Kunjungi portal resmi: \`https://portal.office.com\`.
2. Masuk menggunakan email institusi UPITRA Anda.
3. Setelah berhasil masuk ke dashboard, klik tombol **Install Office** di pojok kanan atas.
4. Unduh installer dan jalankan hingga selesai.`,
    tags: 'office, word, excel, microsoft365, lisensi',
    views: 415,
    helpfulCount: 110,
    createdAt: '2026-08-10T10:15:00.000Z',
  },
  {
    id: 4,
    title: 'Prosedur Peminjaman Alat Multimedia & Zoom Webinar',
    category: 'Multimedia',
    excerpt: 'SOP peminjaman proyektor portabel, mic wireless, dan akun Zoom Room BTIK untuk kegiatan kampus.',
    content: `### Ketentuan Peminjaman Fasilitas Multimedia:
1. Pengajuan wajib dilakukan minimal **H-2 kegiatan** melalui form IT Helpdesk atau surat pengantar BEM/HIMA.
2. Unit multimedia yang tersedia mencakup proyektor, mic wireless, sound portable, dan akun Zoom 500 peserta.
3. Pengambilan dan pengembalian bertempat di Ruang BTIK Lantai 2 Gedung Rektorat.`,
    tags: 'multimedia, proyektor, zoom, webinar, ormawa',
    views: 188,
    helpfulCount: 45,
    createdAt: '2026-08-15T14:00:00.000Z',
  },
];

export const INITIAL_SERVICE_STATUSES: ServiceStatus[] = [
  {
    id: 1,
    serviceName: 'SIAKAD 2.0 UPITRA',
    description: 'Sistem Informasi Akademik Mahasiswa & Dosen',
    status: 'OPERATIONAL',
    uptimePercent: 99.95,
    lastChecked: new Date().toISOString(),
  },
  {
    id: 2,
    serviceName: 'LMS E-Learning Kampus',
    description: 'Platform Moodle Pembelajaran Online',
    status: 'OPERATIONAL',
    uptimePercent: 99.80,
    lastChecked: new Date().toISOString(),
  },
  {
    id: 3,
    serviceName: 'Koneksi Internet & WiFi Kampus',
    description: 'Hotspot Gedung A, Gedung B, dan Perpustakaan',
    status: 'OPERATIONAL',
    uptimePercent: 99.70,
    lastChecked: new Date().toISOString(),
  },
  {
    id: 4,
    serviceName: 'Email Institusi Google Workspace',
    description: 'Layanan email @student.upitra.ac.id dan @upitra.ac.id',
    status: 'OPERATIONAL',
    uptimePercent: 100.00,
    lastChecked: new Date().toISOString(),
  },
  {
    id: 5,
    serviceName: 'Laboratorium Komputer Terpadu',
    description: 'Jaringan LAN dan PC Praktikum Lab 1-3',
    status: 'OPERATIONAL',
    uptimePercent: 99.85,
    lastChecked: new Date().toISOString(),
  },
  {
    id: 6,
    serviceName: 'Portal Keuangan & Tagihan Mahasiswa',
    description: 'Sistem Integrasi Pembayaran Virtual Account',
    status: 'OPERATIONAL',
    uptimePercent: 99.90,
    lastChecked: new Date().toISOString(),
  },
];
